# Generated by Django 3.2 on 2021-04-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
